FROM openjdk:8-jdk-alpine as builder

WORKDIR /app/source

COPY punkapi-beer-assignment .

RUN chmod +x ./mvnw
RUN ./mvnw clean package

FROM openjdk:8-jre-alpine

COPY --from=builder /app/source/target/*.jar /app/app.jar

EXPOSE 8080

RUN addgroup -g 1001 -S appuser && adduser -u 1001 -S appuser -G appuser
USER appuser

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/app.jar"]