version: '3.5'

services:
  example-frontend:
    image: example-frontend
    ports:
      - "5000:5000"
  example-backend:
    image: example-backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis-cache
      - REQUEST_ORIGIN=http://localhost:5000
    depends_on:
      - db
  redis-cache:
    image: redis:6.2.6
  db:
    image: postgres:13.5-alpine
    restart: no
    environment:
      POSTGRES_PASSWORD: postgres
