FROM golang:1.16.3-alpine

WORKDIR /usr/src/app

COPY example-backend .

RUN go build

ENV PORT=8080
ENV REQUEST_ORIGIN=https://example.com

EXPOSE ${PORT}

CMD ./server PORT=$PORT REQUEST_ORIGIN=$REQUEST_ORIGIN
