version: '3.5'

services:
  frontend:
    image: machine-learning-frontend
    ports:
      - "3000:3000"
  backend:
    image: machine-learning-backend
    ports:
      - "5000:5000"
    volumes:
      - model:/src/model
    depends_on:
      - machine-learning-training
  training:
    image: machine-learning-training
    volumes:
      - model:/src/model
      - images:/src/imgs
      - data:/data

volumes:
  images:
  model:
  data:
