version: '3.5'

services:
  proxy:
    image: nginx:1.21.4-alpine
    ports:
      - "8099:80"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend
  frontend:
    image: example-frontend
    networks:
      - frontend
  backend:
    image: example-backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis-cache
      - POSTGRES_HOST=db
    networks:
      - backend
    depends_on:
      - db
  redis-cache:
    image: redis:6.2.2
    networks:
      - backend
  db:
    image: postgres:13.4-alpine
    restart: no
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - backend

networks:
  backend:
    name: backend
  frontend:
    name: frontend
