FROM node:14.16.1-alpine

WORKDIR /usr/src/app

COPY example-frontend .

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

RUN npm install && \
    npm install -g serve && \
    REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL} npm run build

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]
